name: ir_analysis
channels:
  - defaults
dependencies:
  - python=3.7.7
  - pip==20.0.2
  - pip:
    - tqdm==4.46.0
    - click==7.1.2
    - numpy==1.18.4
    - scipy==1.4.1
    - scikit-learn==0.23.1
    - wheel==0.34.2
    - lightgbm==2.3.1
    - optuna==1.5.0
    - pandas==1.0.4
    - jupyter==1.0.0
    - matplotlib==3.2.1
    - seaborn==0.10.1

